### ISSUE TITLE
panic: runtime error: slice bounds out of range [:157479] with capacity 157430

### ISSUE THREAD

**Issue by girino** [bitvora/wot-relay#16]
Got this error, but i think i need to report it on github.com/fiatjaf/eventstore @fiatjaf 

worked smoothly all night yesterday, but this morning, after I restarted it with the new code from master, i got this panic after a few seconds.

Now i'm running it again and no panic yet for 10 minutes or so. I'm not sure how to deal with it.

wot-relay  | panic: runtime error: slice bounds out of range [:157479] with capacity 157430
wot-relay  |
wot-relay  |
wot-relay  | goroutine 51430 [running]:
wot-relay  | github.com/nbd-wtf/go-nostr/binary.Marshal(0x4011107c08)
wot-relay  |    /go/pkg/mod/github.com/nbd-wtf/go-nostr@v0.34.14/binary/hybrid.go:103 +0x63c
wot-relay  | github.com/fiatjaf/eventstore/badger.(*BadgerBackend).SaveEvent-fm.(*BadgerBackend).SaveEvent.func1(0x4011107e80)
wot-relay  |    /go/pkg/mod/github.com/fiatjaf/eventstore@v0.8.1/badger/save.go:29 +0x128
wot-relay  | github.com/dgraph-io/badger/v4.(*DB).Update(0x400dfbbad8?, 0x400dfbbac0)
wot-relay  |    /go/pkg/mod/github.com/dgraph-io/badger/v4@v4.2.0/txn.go:823 +0x84
wot-relay  | github.com/fiatjaf/eventstore/badger.(*BadgerBackend).SaveEvent(...)
wot-relay  |    /go/pkg/mod/github.com/fiatjaf/eventstore@v0.8.1/badger/save.go:14
wot-relay  | github.com/fiatjaf/khatru.(*Relay).AddEvent(0x400011b508, {0x89c608, 0x4010daf400}, 0x4011107c08)
wot-relay  |    /go/pkg/mod/github.com/fiatjaf/khatru@v0.8.0/adding.go:91 +0x60c
wot-relay  | github.com/fiatjaf/khatru.(*Relay).HandleWebsocket.func2.2({0x401164a000?, 0x8bcb4?, 0x4006661770?})
wot-relay  |    /go/pkg/mod/github.com/fiatjaf/khatru@v0.8.0/handlers.go:185 +0xc94
wot-relay  | created by github.com/fiatjaf/khatru.(*Relay).HandleWebsocket.func2 in goroutine 51412
wot-relay  |    /go/pkg/mod/github.com/fiatjaf/khatru@v0.8.0/handlers.go:121 +0x2a0

**Comment by fiatjaf** [comment]
Fixing.

**Comment by barrydeen** [comment]
should be fixed in latest release #17
