### ISSUE TITLE
panic: runtime error: slice bounds out of range [:164456] with capacity 164454

### ISSUE THREAD

**Issue by HolgerHatGarKeineNode** [bitvora/wot-relay#2]
I've had the relay open for an hour now and now I've got this error.

I don't know the Go language. But this seems to be a bug in the code rather than a resource problem right?

Something with slice boundaries...?

```
wot-relay-1  | panic: runtime error: slice bounds out of range [:164456] with capacity 164454
wot-relay-1  |
wot-relay-1  | goroutine 35 [running]:
wot-relay-1  | github.com/nbd-wtf/go-nostr/binary.Marshal(0xc000211688)
wot-relay-1  |  /go/pkg/mod/github.com/nbd-wtf/go-nostr@v0.34.14/binary/hybrid.go:101 +0x745
wot-relay-1  | github.com/fiatjaf/eventstore/lmdb.(*LMDBBackend).SaveEvent.func1(0xc000386300)
wot-relay-1  |  /go/pkg/mod/github.com/fiatjaf/eventstore@v0.8.1/lmdb/save.go:30 +0xc7
wot-relay-1  | github.com/PowerDNS/lmdb-go/lmdb.(*Txn).runOpTerm(0xc000386300, 0x0?)
wot-relay-1  |  /go/pkg/mod/github.com/!power!d!n!s/lmdb-go@v1.9.2/lmdb/txn.go:174 +0x5f
wot-relay-1  | github.com/PowerDNS/lmdb-go/lmdb.(*Env).run(0xc00018b0b0?, 0x1, 0x0?, 0xc000086ce8)
wot-relay-1  |  /go/pkg/mod/github.com/!power!d!n!s/lmdb-go@v1.9.2/lmdb/env.go:511 +0xab
wot-relay-1  | github.com/PowerDNS/lmdb-go/lmdb.(*Env).Update(...)
wot-relay-1  |  /go/pkg/mod/github.com/!power!d!n!s/lmdb-go@v1.9.2/lmdb/env.go:478
wot-relay-1  | github.com/fiatjaf/eventstore/lmdb.(*LMDBBackend).SaveEvent(0x40b492?, {0xc0019241c0?, 0xc000086eb8?}, 0xb8b401?)
wot-relay-1  |  /go/pkg/mod/github.com/fiatjaf/eventstore@v0.8.1/lmdb/save.go:20 +0x6f
wot-relay-1  | github.com/fiatjaf/khatru.(*Relay).AddEvent(0xc00016e388, {0x9269c0, 0xb8b420}, 0xc000211688)
wot-relay-1  |  /go/pkg/mod/github.com/fiatjaf/khatru@v0.8.0/adding.go:91 +0x7b9
wot-relay-1  | main.archiveTrustedNotes(0xc00016e388)
wot-relay-1  |  /app/main.go:229 +0x1b5
wot-relay-1  | created by main.main in goroutine 1
wot-relay-1  |  /app/main.go:51 +0x376
```

My trust network size:
`wot-relay-1  | trust network size: 4865`

**Comment by barrydeen** [comment]
This is fixed now in latest.
